name:                que
version:             0.1.0
github:              "vanetix/que"
license:             BSD3
author:              "Matt McFarland"
maintainer:          "783024+vanetix@users.noreply.github.com"
copyright:           "2020 Matt McFarland"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vanetix/que#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - ansi-terminal
  - boxes
  - containers
  - directory
  - filepath
  - text
  - time
  - yaml

executables:
  que:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative
    - time
    - que

tests:
  que-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - hspec
    - time
    - que
